apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pytbak-helm.fullname" . }}-pytbak-stable
  labels:
    app: pytbak
    track: pytbak-stable
  {{- include "pytbak-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pytbakStable.replicas }}
  selector:
    matchLabels:
      app: pytbak
      track: pytbak-stable
    {{- include "pytbak-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: pytbak
        track: pytbak-stable
      {{- include "pytbak-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.pytbakStable.pytbak.image.repository }}:{{ .Values.pytbakStable.pytbak.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 4
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: pytbak
        ports:
        - containerPort: 5000
          name: http
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /api/
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 4
          periodSeconds: 2
          successThreshold: 3
          timeoutSeconds: 2
        resources: {{- toYaml .Values.pytbakStable.pytbak.resources | nindent 10 }}