apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "pytbak-helm.fullname" . }}-quota
  labels:
  {{- include "pytbak-helm.labels" . | nindent 4 }}
spec:
  hard:
    cpu: 900m
    memory: 750Mi
    pods: "3"